version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  deploying:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install heroku then push
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku git:remote -a $HEROKU_APP_NAME
            echo "machine api.heroku.com
              login $HEROKU_USERNAME
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_USERNAME
              password $HEROKU_API_KEY" > ~/.netrc
            git push heroku main:master
  testing:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - run: yarn build
      - run: yarn test

workflows:
  ci:
    jobs:
      - testing
      - approve_deployment:
          name: "approve-deployment"
          type: approval
          requires:
            - testing
          filters:
            branches:
              only:
                - main
      - deploying:
          requires:
            - "approve-deployment"
